const items = [
  {
      id: '001',
      image: '../images/products/product1.webp',
      company: 'MANGO',
      item_name: 'Turtle Neck T-Shirt',
      original_price: 1045,
      current_price: 606,
      discount_percentage: 42,
      return_period: 14,
      delivery_date: '10 Oct 2024',
      rating: {
          stars: 4.5,
          count: 1400,
           },
        },
      {
        id: '002',
        image: '../images/products/product2.webp',
        company: 'MANGO',
        item_name: 'Short Sleeved T-Shirt',
        original_price: 2599,
        current_price: 1507,
        discount_percentage: 42,
        return_period: 14,
        delivery_date: '10 Oct 2024',
        rating: {
            stars: 4.3,
            count: 24,
        },
      },
    {
        id: '003',
        image: '../images/products/product3.webp',
        company: 'ROADSTER',
        item_name: 'Pure Cotton T-Shirt',
        original_price: 1599,
        current_price: 495,
        discount_percentage: 69,
        return_period: 14,
        delivery_date: '10 Oct 2024',
        rating: {
            stars: 4.1,
            count: 249,
        },
    },
    {
        id: '004',
        image: '../images/products/product4.webp',
        company: 'KOTTY',
        item_name: 'Over-sized T-Shirt',
        original_price: 999,
        current_price: 999,
        discount_percentage: 0,
        return_period: 14,
        delivery_date: '10 Oct 2024',
        rating: {
            stars: 5.0,
            count: 10,
        },
    },
    {
        id: '005',
        image: '../images/products/product5.webp',
        company: 'HRX by HRITIK ROSHAN',
        item_name: 'Dry fit T-Shirt',
        original_price: 1399,
        current_price: 489,
        discount_percentage: 65,
        return_period: 14,
        delivery_date: '10 Oct 2024',
        rating: {
            stars: 4.2,
            count: 3500,
        },
    },
    {
        id: '006',
        image: '../images/products/product6.webp',
        company: 'Bewakoof',
        item_name: 'Printed Cotton T-Shirt',
        original_price: 149,
        current_price: 149,
        discount_percentage: 0,
        return_period: 14,
        delivery_date: '10 Oct 2024',
        rating: {
            stars: 0.0,
            count: 0,
        },
    },
    {
        id: '007',
        image: '../images/products/product7.webp',
        company: 'DILLINGER',
        item_name: 'Pure Cotton T-Shirt',
        original_price: 1599,
        current_price: 639,
        discount_percentage: 60,
        return_period: 14,
        delivery_date: '10 Oct 2024',
        rating: {
            stars: 4.2,
            count: 388,
        },
    },
    {
        id: '008',
        image: '../images/products/product8.webp',
        company: 'ROADSTER',
        item_name: 'Plus Sized T-Shirt',
        original_price: 285,
        current_price: 142,
        discount_percentage: 50,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.2,
            count: 5200,
        },
    }
];